/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  OLMap as OlMap
} from './components/ol-map/ol-map';

declare global {
  interface HTMLOlMapElement extends OlMap, HTMLElement {
  }
  var HTMLOlMapElement: {
    prototype: HTMLOlMapElement;
    new (): HTMLOlMapElement;
  };
  interface HTMLElementTagNameMap {
    "ol-map": HTMLOlMapElement;
  }
  interface ElementTagNameMap {
    "ol-map": HTMLOlMapElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "ol-map": JSXElements.OlMapAttributes;
    }
  }
  namespace JSXElements {
    export interface OlMapAttributes extends HTMLAttributes {
      latitude?: number;
      longitude?: number;
      zoom?: number;
    }
  }
}

